import React from "react";
import { money, formatDateTime } from "../lib/format";
import type { Settings } from "../types";

// A4 purchase-invoice equivalent of ReceiptPreview's 58mm dual-copy receipt:
// one finalized purchase renders into a Supplier Copy and an Office Copy so
// they can never diverge, printed via the same hidden #print-root mechanism
// (see index.css) but sized for A4 instead of 58mm.
export interface PurchaseInvoiceData {
  invoiceNo: string;
  poNo?: string | null;
  date: string;
  supplierName?: string;
  supplierPhone?: string;
  items: Array<{ name: string; nameUrdu?: string; qty: number; unit: string; rate: number; amount: number }>;
  subtotal: number;
  discount: number;
  tax: number;
  total: number;
  paymentMethod: string;
  paid: number;
  balance: number;
  notes?: string;
}

function InvoiceCopy({ data, settings, label }: { data: PurchaseInvoiceData; settings: Settings; label: string }) {
  return (
    <div className="invoice-copy">
      <div className="inv-head">
        <div>
          <div className="inv-business">{settings.business_name || "Haji Abdul Manan & Abdul Hanan"}</div>
          <div className="inv-tagline">{settings.business_title || "Atta Dealer Pishin"}</div>
          {settings.address && <div className="inv-small">{settings.address}</div>}
          {settings.phone && <div className="inv-small">{settings.phone}</div>}
        </div>
        <div className="inv-title">
          <div className="inv-title-main">PURCHASE INVOICE</div>
          <div className="inv-small">{data.invoiceNo}</div>
          {data.poNo && <div className="inv-small">Ref PO: {data.poNo}</div>}
        </div>
      </div>
      <div className="inv-divider" />
      <div className="inv-meta">
        <div>
          <div className="inv-small bold">Supplier</div>
          <div>{data.supplierName || "—"}</div>
          {data.supplierPhone && <div className="inv-small">{data.supplierPhone}</div>}
        </div>
        <div>
          <div className="inv-small bold">Date</div>
          <div>{formatDateTime(data.date)}</div>
        </div>
      </div>
      <table className="inv-table">
        <thead>
          <tr><th>#</th><th>Product</th><th>Qty</th><th>Rate</th><th>Amount</th></tr>
        </thead>
        <tbody>
          {data.items.map((it, i) => (
            <tr key={i}>
              <td>{i + 1}</td>
              <td>{it.name}{it.nameUrdu && <span className="inv-small"> — {it.nameUrdu}</span>}</td>
              <td>{it.qty} {it.unit}</td>
              <td>{money(it.rate)}</td>
              <td>{money(it.amount)}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="inv-totals">
        <div className="row"><span>Subtotal</span><span>{money(data.subtotal)}</span></div>
        {data.discount > 0 && <div className="row"><span>Discount</span><span>-{money(data.discount)}</span></div>}
        {data.tax > 0 && <div className="row"><span>Tax</span><span>{money(data.tax)}</span></div>}
        <div className="row bold total"><span>TOTAL</span><span>{money(data.total)}</span></div>
        <div className="row"><span>Payment ({data.paymentMethod})</span><span>{money(data.paid)}</span></div>
        <div className="row bold"><span>Balance Payable</span><span>{money(data.balance)}</span></div>
      </div>
      {data.notes && <div className="inv-small" style={{ marginTop: "4mm" }}>Notes: {data.notes}</div>}
      <div className="inv-divider" />
      <div className="inv-footer">
        <span>{label}</span>
        <span>Generated by ShopManager — internal document, not a tax invoice unless registered.</span>
      </div>
    </div>
  );
}

export function PurchaseInvoicePreview({ data, settings, variant = "hidden" }: { data: PurchaseInvoiceData; settings: Settings; variant?: "hidden" | "visible" }) {
  const copies = (
    <>
      <InvoiceCopy data={data} settings={settings} label="SUPPLIER COPY" />
      <InvoiceCopy data={data} settings={settings} label="OFFICE COPY" />
    </>
  );
  if (variant === "visible") return <div className="flex flex-col items-center gap-6">{copies}</div>;
  return <div id="print-root" className="print-a4">{copies}</div>;
}
